---
output:
  html_document:
    theme: cosmo
---

# This is another one!

This #TidyTuesday plot originally by Charlie Gallagher
is cute! 🥧

The [final one](https://github.com/charlie-gallagher/tidy-tuesday/tree/master/extinct_plants) is even better!

```{r setup, include = FALSE}
library(tidyverse)
```

```{r data, include = FALSE}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')
```


```{r plot, echo = FALSE, message = FALSE, warning = FALSE}
group_threats <- plants %>% 
  group_by(group) %>% 
  summarize(
    aa = mean(threat_AA, na.rm = TRUE),
    bru = mean(threat_BRU, na.rm = TRUE),
    rcd = mean(threat_RCD, na.rm = TRUE),
    isgd = mean(threat_ISGD, na.rm = TRUE),
    epm = mean(threat_EPM, na.rm = TRUE),
    cc = mean(threat_CC, na.rm = TRUE),
    hid = mean(threat_HID, na.rm = TRUE),
    p = mean(threat_P, na.rm = TRUE),
    ts = mean(threat_TS, na.rm = TRUE),
    nsm = mean(threat_NSM, na.rm = TRUE),
    ge = mean(threat_GE, na.rm = TRUE),
    na = mean(threat_NA, na.rm = TRUE)
  ) %>% 
  pivot_longer(cols = c(aa, bru, rcd, isgd, epm, cc, hid, p, ts, nsm, ge, na),
               names_to = 'threat', values_to = 'pct_species') %>% 
  mutate(c_pct_species = 1 - pct_species) %>% 
  pivot_longer(cols = c(pct_species, c_pct_species)) %>% 
  ungroup()

threat_palette <- c("#d8d3cd", "#158467")

group_threats %>% 
  mutate(threat = toupper(threat)) %>% 
  ggplot() + 
  geom_col(aes(x = "", y = value, group = name, fill = name),
           size = 1, color = NA) + 
  scale_fill_manual(values = threat_palette) + 
  guides(fill = FALSE) + 
  facet_grid(rows = vars(group), cols = vars(threat)) +
  coord_polar('y') + 
  theme_void() + 
  theme(
    strip.background = element_blank()
  )

```
